<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\CalculatorController' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Controller\\ControllerTrait.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Controller\\AbstractController.php';
include_once $this->targetDirs[3].'\\src\\Controller\\CalculatorController.php';
include_once $this->targetDirs[3].'\\src\\Service\\ArithmeticCalculatorService.php';
include_once $this->targetDirs[3].'\\src\\Service\\Strategy\\OperatorContext.php';
include_once $this->targetDirs[3].'\\src\\Service\\Strategy\\CalculatorInterface.php';
include_once $this->targetDirs[3].'\\src\\Service\\Strategy\\BitwiseAndStrategy.php';
include_once $this->targetDirs[3].'\\src\\Service\\Strategy\\BitwiseOrStrategy.php';
include_once $this->targetDirs[3].'\\src\\Service\\Strategy\\DivisionStrategy.php';
include_once $this->targetDirs[3].'\\src\\Service\\Strategy\\MinusStrategy.php';
include_once $this->targetDirs[3].'\\src\\Service\\Strategy\\MultiplicationStrategy.php';
include_once $this->targetDirs[3].'\\src\\Service\\Strategy\\PlusStrategy.php';

$a = new \App\Service\Strategy\OperatorContext();
$a->addStrategy(new \App\Service\Strategy\BitwiseAndStrategy());
$a->addStrategy(new \App\Service\Strategy\BitwiseOrStrategy());
$a->addStrategy(new \App\Service\Strategy\DivisionStrategy());
$a->addStrategy(new \App\Service\Strategy\MinusStrategy());
$a->addStrategy(new \App\Service\Strategy\MultiplicationStrategy());
$a->addStrategy(new \App\Service\Strategy\PlusStrategy());

$this->services['App\\Controller\\CalculatorController'] = $instance = new \App\Controller\CalculatorController(new \App\Service\ArithmeticCalculatorService($a));

$instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'form.factory' => ['services', 'form.factory', 'getForm_FactoryService.php', true],
    'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
    'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
    'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
    'router' => ['services', 'router', 'getRouterService', false],
    'serializer' => ['services', 'serializer', 'getSerializerService.php', true],
    'session' => ['services', 'session', 'getSessionService.php', true],
    'twig' => ['services', 'twig', 'getTwigService', false],
], [
    'form.factory' => '?',
    'http_kernel' => '?',
    'parameter_bag' => '?',
    'request_stack' => '?',
    'router' => '?',
    'serializer' => '?',
    'session' => '?',
    'twig' => '?',
]))->withContext('App\\Controller\\CalculatorController', $this));

return $instance;
