<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOFxaCJF\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOFxaCJF/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOFxaCJF.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOFxaCJF\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOFxaCJF\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OFxaCJF',
    'container.build_id' => 'f2d450cc',
    'container.build_time' => 1565783613,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOFxaCJF');
